<?php
Route::namespace('Admin')->prefix('admin')->group(function(){
    Route::prefix('home')->group(function(){
        Route::get('index',[
            'uses'=>'HomeController@index',
            'as'=>'admin.home.index'
        ]);
    });
    Route::prefix('category')->group(function(){
        Route::get('index',[
            'uses'=>'CategoryController@index',
            'as'=>'admin.category.index'
        ]);
        Route::get('add',[
            'uses'=>'CategoryController@add',
            'as'=>'admin.category.add'
        ]);
        Route::post('add',[
            'uses'=>'CategoryController@postAdd',
            'as'=>'admin.category.add'
        ]);
        Route::get('edit/{id}',[
            'uses'=>'CategoryController@edit',
            'as'=>'admin.category.edit'
        ]);
        Route::post('edit/{id}',[
            'uses'=>'CategoryController@postEdit',
            'as'=>'admin.category.edit'
        ]);
        Route::get('del/{id}',[
            'uses'=>'CategoryController@del',
            'as'=>'admin.category.del'
        ]);
    });
});